name: dart_grpc_server
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  grpc: ^3.2.4
  protobuf: ^3.1.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
